---

- name: Copy file 
  become: true
  hosts: all

  vars:
    spath: /etc/test.conf
    dpath: /home/test.conf
  tasks:
  - name: copy file 
    copy:
       src: "{{spath}}"
       dest: "{{dpath}}"
    #   owner: 
    #  group: 
    #  mode: 
