---

- name: Vault for git
  hosts: all
  become: true

  vars_files:
   - /home/ubuntu/uservault.yml

  tasks:
  - name: Git repo
    git:  https://{{ username }}:{{ password }}@github.com/Vjy05git/Vault.git
    dest: /home/ubuntu/repo