---

- name: Vault for git
  hosts: all
  become: true

  vars_files:
   - /home/ubuntu/uservault.yml

  tasks:
  - name: Git installation
    dnf:
     name: git
     state: present
     
  - name: Git repo
    git:
     repo: https://Vjy05git:{{password}}@github.com/Vjy05git/Vault.git
     dest: /home/ubuntu/
